pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Terraform & Zip') {
      steps {
        dir('second-pipeline') {
          sh 'zip lambda.zip lambda_function.py'
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }

    stage('Update Lambda') {
      steps {
        dir('second-pipeline') {
          sh """
            aws lambda update-function-code \
              --function-name oleg-tf-lambda \
              --zip-file fileb://lambda.zip \
              --region us-east-1
          """
        }
      }
    }
  }
}
